// <auto-generated />
using System;
using System.Collections.Generic;
using LeadingEDJE.Leap.Api.Platform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeadingEDJE.Leap.Api.Platform.Data.Migrations
{
    [DbContext(typeof(LeapDbContext))]
    partial class LeapDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Modules.Compass.BillableTimeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("billable_time_category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_name");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LegacyTpsId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("legacy_tps_id");

                    b.HasKey("Id")
                        .HasName("pk_billable_time_category");

                    b.HasIndex("LegacyTpsId")
                        .IsUnique()
                        .HasDatabaseName("ux_billable_time_category_legacy_tps_id");

                    b.HasIndex("ClientId", "CategoryName")
                        .IsUnique()
                        .HasDatabaseName("ux_billable_time_category_client_id_category_name");

                    b.ToTable("billable_time_category", "compass");
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Modules.Compass.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client_name");

                    b.Property<int?>("InvoiceFrequencyTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("invoice_frequency_type_id");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_internal");

                    b.Property<string>("LegacyTpsId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("legacy_tps_id");

                    b.Property<DateOnly?>("MsaSignedDate")
                        .HasColumnType("date")
                        .HasColumnName("msa_signed_date");

                    b.Property<DateOnly?>("NdaSignedDate")
                        .HasColumnType("date")
                        .HasColumnName("nda_signed_date");

                    b.HasKey("Id")
                        .HasName("pk_client");

                    b.HasIndex("ClientName")
                        .IsUnique()
                        .HasDatabaseName("ux_client_client_name");

                    b.HasIndex("InvoiceFrequencyTypeId")
                        .HasDatabaseName("ix_client_invoice_frequency_type_id");

                    b.HasIndex("LegacyTpsId")
                        .IsUnique()
                        .HasDatabaseName("ux_client_legacy_tps_id");

                    b.ToTable("client", "compass");
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Modules.Compass.ClientAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("client_assignment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int?>("InvoiceFrequencyTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("invoice_frequency_type_id");

                    b.Property<string>("LegacyTpsId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("legacy_tps_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_client_assignment");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_client_assignment_client_id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_client_assignment_employee_id");

                    b.HasIndex("InvoiceFrequencyTypeId")
                        .HasDatabaseName("ix_client_assignment_invoice_frequency_type_id");

                    b.HasIndex("LegacyTpsId")
                        .IsUnique()
                        .HasDatabaseName("ux_client_assignment_legacy_tps_id");

                    b.ToTable("client_assignment", "compass", t =>
                        {
                            t.HasCheckConstraint("ck_client_assignment_end_on_or_after_start", "end_date IS NULL OR end_date >= start_date");
                        });
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Modules.Compass.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanSubmitUnder40")
                        .HasColumnType("boolean")
                        .HasColumnName("can_submit_under_40");

                    b.Property<int?>("CoachEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("coach_employee_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int>("EmployeeTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_type_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<bool>("IncludeInPayroll")
                        .HasColumnType("boolean")
                        .HasColumnName("include_in_payroll");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeliveryTeam")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_delivery_team");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("LegacyTpsId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("legacy_tps_id");

                    b.Property<string>("StateOfResidence")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("state_of_residence");

                    b.Property<bool>("TimesheetRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("timesheet_required");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("America/New_York")
                        .HasColumnName("timezone");

                    b.HasKey("Id")
                        .HasName("pk_employee");

                    b.HasIndex("CoachEmployeeId")
                        .HasDatabaseName("ix_employee_coach_employee_id");

                    b.HasIndex("EmployeeTypeId")
                        .HasDatabaseName("ix_employee_employee_type_id");

                    b.HasIndex("LastName")
                        .HasDatabaseName("ix_employee_last_name");

                    b.HasIndex("LegacyTpsId")
                        .IsUnique()
                        .HasDatabaseName("ux_employee_legacy_tps_id");

                    b.ToTable("employee", "compass", t =>
                        {
                            t.HasCheckConstraint("ck_employee_state_of_residence_us", "state_of_residence IN ('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY')");
                        });
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Modules.Compass.EmployeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("employee_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type_name");

                    b.HasKey("Id")
                        .HasName("pk_employee_type");

                    b.HasIndex("TypeName")
                        .IsUnique()
                        .HasDatabaseName("ux_employee_type_type_name");

                    b.ToTable("employee_type", "compass");
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Modules.Compass.InvoiceFrequencyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("invoice_frequency_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type_name");

                    b.HasKey("Id")
                        .HasName("pk_invoice_frequency_type");

                    b.HasIndex("TypeName")
                        .IsUnique()
                        .HasDatabaseName("ux_invoice_frequency_type_type_name");

                    b.ToTable("invoice_frequency_type", "compass");
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Modules.Compass.Sow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sow_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientAssignmentId")
                        .HasColumnType("integer")
                        .HasColumnName("client_assignment_id");

                    b.Property<bool>("HasPassedApplicationValidation")
                        .HasColumnType("boolean")
                        .HasColumnName("has_passed_application_validation");

                    b.Property<string>("LegacyTpsId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("legacy_tps_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<bool>("RateIncrease")
                        .HasColumnType("boolean")
                        .HasColumnName("rate_increase");

                    b.Property<DateOnly>("SowEndDate")
                        .HasColumnType("date")
                        .HasColumnName("sow_end_date");

                    b.Property<DateOnly>("SowStartDate")
                        .HasColumnType("date")
                        .HasColumnName("sow_start_date");

                    b.Property<string>("SowType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sow_type");

                    b.HasKey("Id")
                        .HasName("pk_sow");

                    b.HasIndex("LegacyTpsId")
                        .IsUnique()
                        .HasDatabaseName("ux_sow_legacy_tps_id");

                    b.HasIndex("ClientAssignmentId", "SowEndDate")
                        .HasDatabaseName("ix_sow_client_assignment_id_sow_end_date");

                    b.ToTable("sow", "compass", t =>
                        {
                            t.HasCheckConstraint("ck_sow_end_on_or_after_start", "sow_type = 'LegacyMigrated' OR sow_end_date >= sow_start_date");

                            t.HasCheckConstraint("ck_sow_rate_increase_requires_extension", "NOT rate_increase OR sow_type = 'SowExtension'");

                            t.HasCheckConstraint("ck_sow_type_is_known", "sow_type IN ('InitialContract', 'SowExtension', 'LegacyMigrated')");
                        });
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Platform.Domain.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.PrimitiveCollection<List<string>>("EffectiveRoles")
                        .HasColumnType("text[]")
                        .HasColumnName("effective_roles");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("triggered_by");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Platform.Domain.NotificationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("employee_id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("FromAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("from_address");

                    b.Property<string>("FromName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("from_name");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("notification_type");

                    b.Property<DateOnly>("PeriodWeekStart")
                        .HasColumnType("date")
                        .HasColumnName("period_week_start");

                    b.Property<string>("RecipientEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("recipient_email");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("SlackUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slack_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_notification_logs");

                    b.HasIndex("EmployeeId", "NotificationType", "PeriodWeekStart")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_log_idempotency");

                    b.ToTable("notification_logs", (string)null);
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Platform.Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("EdjeId")
                        .HasColumnType("uuid")
                        .HasColumnName("edje_id");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_name");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_people");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_people_email");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Platform.Domain.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_system_settings");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Platform.Domain.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EdjeId")
                        .HasColumnType("uuid")
                        .HasColumnName("edje_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.HasIndex("EdjeId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ix_user_roles_edje_id_role");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Modules.Compass.BillableTimeCategory", b =>
                {
                    b.HasOne("LeadingEDJE.Leap.Api.Modules.Compass.Client", "Client")
                        .WithMany("BillableTimeCategories")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_billable_time_category_client_client_id");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Modules.Compass.Client", b =>
                {
                    b.HasOne("LeadingEDJE.Leap.Api.Modules.Compass.InvoiceFrequencyType", "InvoiceFrequencyType")
                        .WithMany("Clients")
                        .HasForeignKey("InvoiceFrequencyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_client_invoice_frequency_type_invoice_frequency_type_id");

                    b.Navigation("InvoiceFrequencyType");
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Modules.Compass.ClientAssignment", b =>
                {
                    b.HasOne("LeadingEDJE.Leap.Api.Modules.Compass.Client", "Client")
                        .WithMany("ClientAssignments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_client_assignment_client_client_id");

                    b.HasOne("LeadingEDJE.Leap.Api.Modules.Compass.Employee", "Employee")
                        .WithMany("ClientAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_client_assignment_employee_employee_id");

                    b.HasOne("LeadingEDJE.Leap.Api.Modules.Compass.InvoiceFrequencyType", "InvoiceFrequencyType")
                        .WithMany()
                        .HasForeignKey("InvoiceFrequencyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_client_assignment_invoice_frequency_type_invoice_frequency_");

                    b.Navigation("Client");

                    b.Navigation("Employee");

                    b.Navigation("InvoiceFrequencyType");
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Modules.Compass.Employee", b =>
                {
                    b.HasOne("LeadingEDJE.Leap.Api.Modules.Compass.Employee", "Coach")
                        .WithMany("Coachees")
                        .HasForeignKey("CoachEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_employee_employee_coach_employee_id");

                    b.HasOne("LeadingEDJE.Leap.Api.Modules.Compass.EmployeeType", "EmployeeType")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_employee_type_employee_type_id");

                    b.Navigation("Coach");

                    b.Navigation("EmployeeType");
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Modules.Compass.Sow", b =>
                {
                    b.HasOne("LeadingEDJE.Leap.Api.Modules.Compass.ClientAssignment", "ClientAssignment")
                        .WithMany("Sows")
                        .HasForeignKey("ClientAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sow_client_assignment_client_assignment_id");

                    b.Navigation("ClientAssignment");
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Modules.Compass.Client", b =>
                {
                    b.Navigation("BillableTimeCategories");

                    b.Navigation("ClientAssignments");
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Modules.Compass.ClientAssignment", b =>
                {
                    b.Navigation("Sows");
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Modules.Compass.Employee", b =>
                {
                    b.Navigation("ClientAssignments");

                    b.Navigation("Coachees");
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Modules.Compass.EmployeeType", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("LeadingEDJE.Leap.Api.Modules.Compass.InvoiceFrequencyType", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
