// Character and item art. Same convention as tiles.js: one character per pixel,
// mapped through each sprite's palette map. Here '.' IS meaningful — it's
// transparent, so sprites read correctly over any background.
//
// Wren's left-facing frames are generated by mirroring the right-facing ones,
// so there's only one side profile to maintain.

import { bakeFrames, flipH, silhouette, bake } from '../engine/pixels.js';

const HERO = {
  g: 'tunic',
  G: 'tunicDark',
  s: 'skin',
  S: 'skinDark',
  k: 'black',
  w: 'white',
};

const FOE = {
  e: 'enemy',
  E: 'enemyDark',
  p: 'enemyPale',
  k: 'black',
};

const OLD = {
  r: 'robe',
  R: 'robeDark',
  s: 'skin',
  k: 'black',
  y: 'gold',
};

const METAL = { b: 'sword', d: 'grayDark', h: 'swordHilt', w: 'white' };
const STONE = { r: 'rock', d: 'rockDark', L: 'rockLight' };
const GEM = { y: 'rupee', d: 'rockDark', w: 'white' };
const LIFE = { h: 'heart', d: 'heartEmpty', w: 'white' };
const PUFF = { w: 'white', g: 'gray' };

// --- Wren -------------------------------------------------------------------

const WREN_DOWN = {
  palette: HERO,
  frames: [
    [
      '................',
      '.....GGGGGG.....',
      '....GggggggG....',
      '...GggggggggG...',
      '...GssssssssG...',
      '...ssskssksss...',
      '...ssskssksss...',
      '....ssssssss....',
      '..sggGGGGGGggs..',
      '..sggGGGGGGggs..',
      '...gGGGGGGGGg...',
      '...gGGGGGGGGg...',
      '....GGGGGGGG....',
      '....kkk..kkk....',
      '....kkk..kkk....',
      '................',
    ],
    [
      '................',
      '.....GGGGGG.....',
      '....GggggggG....',
      '...GggggggggG...',
      '...GssssssssG...',
      '...ssskssksss...',
      '...ssskssksss...',
      '....ssssssss....',
      '...sggGGGGGGs...',
      '...sggGGGGGGs...',
      '...gGGGGGGGGg...',
      '...gGGGGGGGGg...',
      '....GGGGGGGG....',
      '...kkk....kkk...',
      '...kkk....kkk...',
      '................',
    ],
  ],
};

const WREN_UP = {
  palette: HERO,
  frames: [
    [
      '................',
      '.....GGGGGG.....',
      '....GggggggG....',
      '...GggggggggG...',
      '...GggggggggG...',
      '...GggggggggG...',
      '...GggggggggG...',
      '....gggggggg....',
      '..sggGGGGGGggs..',
      '..sggGGGGGGggs..',
      '...gGGGGGGGGg...',
      '...gGGGGGGGGg...',
      '....GGGGGGGG....',
      '....kkk..kkk....',
      '....kkk..kkk....',
      '................',
    ],
    [
      '................',
      '.....GGGGGG.....',
      '....GggggggG....',
      '...GggggggggG...',
      '...GggggggggG...',
      '...GggggggggG...',
      '...GggggggggG...',
      '....gggggggg....',
      '...sggGGGGGGs...',
      '...sggGGGGGGs...',
      '...gGGGGGGGGg...',
      '...gGGGGGGGGg...',
      '....GGGGGGGG....',
      '...kkk....kkk...',
      '...kkk....kkk...',
      '................',
    ],
  ],
};

const WREN_RIGHT = {
  palette: HERO,
  frames: [
    [
      '................',
      '.....GGGGGG.....',
      '....GgggggggG...',
      '....GggggggggG..',
      '....Gssssssss...',
      '....sssskssss...',
      '.....ssssssss...',
      '....gGGGGGGg....',
      '...sgGGGGGGGs...',
      '...sgGGGGGGGs...',
      '....GGGGGGGG....',
      '....GGGGGGGG....',
      '.....kkkkk......',
      '.....kkkkk......',
      '................',
      '................',
    ],
    [
      '................',
      '.....GGGGGG.....',
      '....GgggggggG...',
      '....GggggggggG..',
      '....Gssssssss...',
      '....sssskssss...',
      '.....ssssssss...',
      '....gGGGGGGg....',
      '....gGGGGGGGs...',
      '....gGGGGGGGs...',
      '....GGGGGGGG....',
      '....GGGGGGGG....',
      '....kkkkk.......',
      '....kkkkk.......',
      '................',
      '................',
    ],
  ],
};

// --- Spitter ----------------------------------------------------------------

const SPITTER = {
  palette: FOE,
  frames: [
    [
      '................',
      '................',
      '....EEEEEEEE....',
      '..EEeeeeeeeeEE..',
      '.EeeeeeeeeeeeeE.',
      '.EeeppeeeeppeeE.',
      '.EeepkeeeepkeeE.',
      '.EeeppeeeeppeeE.',
      '.EeeeeeeeeeeeeE.',
      '.EeeeeeeeeeeeeE.',
      '..EEeeeeeeeeEE..',
      '....EEEEEEEE....',
      '..EE..EE..EE....',
      '..EE..EE..EE....',
      '................',
      '................',
    ],
    [
      '................',
      '................',
      '....EEEEEEEE....',
      '..EEeeeeeeeeEE..',
      '.EeeeeeeeeeeeeE.',
      '.EeeppeeeeppeeE.',
      '.EeepkeeeepkeeE.',
      '.EeeppeeeeppeeE.',
      '.EeeeeeeeeeeeeE.',
      '.EeeeeeeeeeeeeE.',
      '..EEeeeeeeeeEE..',
      '....EEEEEEEE....',
      '....EE..EE..EE..',
      '....EE..EE..EE..',
      '................',
      '................',
    ],
  ],
};

// --- The Hermit -------------------------------------------------------------

const HERMIT = {
  palette: OLD,
  frames: [
    [
      '................',
      '.....RRRRRR.....',
      '....RrrrrrrR....',
      '...RrrrrrrrrR...',
      '...RssssssssR...',
      '...ssskssksss...',
      '...ssssssssss...',
      '....rsssssssr...',
      '...rrrrrrrrrrr..',
      '..rrrrrrrrrrrr..',
      '..rrRrrrrrrRrr..',
      '..rrrrrrrrrrrr..',
      '...rrrrrrrrrr...',
      '...RRRRRRRRRR...',
      '....kkk..kkk....',
      '................',
    ],
  ],
};

// --- Items and effects ------------------------------------------------------

const ROCK_SHOT = {
  palette: STONE,
  frames: [
    [
      '..dddd..',
      '.dLLLLd.',
      'dLLrrLLd',
      'dLrrrrLd',
      'dLrrrrLd',
      'dLLrrLLd',
      '.dLLLLd.',
      '..dddd..',
    ],
  ],
};

const RUPEE = {
  palette: GEM,
  frames: [
    [
      '..dd..',
      '.dyyd.',
      'dywyyd',
      'dyyyyd',
      'dyyyyd',
      'dywyyd',
      '.dyyd.',
      '..dd..',
    ],
  ],
};

const HEART_FULL = [
  '.hh..hh.',
  'hhhhhhhh',
  'hhhhhhhh',
  'hhhhhhhh',
  '.hhhhhh.',
  '..hhhh..',
  '...hh...',
  '........',
];

const HEART_HALF = [
  '.hh..dd.',
  'hhhhdddd',
  'hhhhdddd',
  'hhhhdddd',
  '.hhhddd.',
  '..hhdd..',
  '...hd...',
  '........',
];

const HEART_EMPTY = [
  '.dd..dd.',
  'dddddddd',
  'dddddddd',
  'dddddddd',
  '.dddddd.',
  '..dddd..',
  '...dd...',
  '........',
];

const SWORD_UP = {
  palette: METAL,
  frames: [
    [
      '..bb..',
      '..bb..',
      '..bb..',
      '..bb..',
      '..bb..',
      '..bb..',
      '..bb..',
      '..bb..',
      '..bb..',
      '.dbbd.',
      'hhhhhh',
      '..hh..',
      '..hh..',
      '......',
      '......',
      '......',
    ],
  ],
};

const SWORD_DOWN = {
  palette: METAL,
  frames: [
    [
      '......',
      '......',
      '......',
      '..hh..',
      '..hh..',
      'hhhhhh',
      '.dbbd.',
      '..bb..',
      '..bb..',
      '..bb..',
      '..bb..',
      '..bb..',
      '..bb..',
      '..bb..',
      '..bb..',
      '..bb..',
    ],
  ],
};

const SWORD_RIGHT = {
  palette: METAL,
  frames: [
    [
      '......hh........',
      '..hhhhhhdbbbbbbb',
      '..hhhhhhdbbbbbbb',
      '......hh........',
    ],
  ],
};

const POOF = {
  palette: PUFF,
  frames: [
    [
      '................',
      '................',
      '................',
      '......wwww......',
      '.....wggggw.....',
      '....wggwwggw....',
      '....wgwwwwgw....',
      '....wgwwwwgw....',
      '....wggwwggw....',
      '.....wggggw.....',
      '......wwww......',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    [
      '................',
      '...w..w..w..w...',
      '................',
      '..w..wwwwww..w..',
      '....wg....gw....',
      '..w.g......g.w..',
      '....g......g....',
      '....g......g....',
      '..w.g......g.w..',
      '....wg....gw....',
      '..w..wwwwww..w..',
      '................',
      '...w..w..w..w...',
      '................',
      '................',
      '................',
    ],
  ],
};

/** Baked art, populated by bakeSprites(). */
export const art = {};

export function bakeSprites() {
  const right = bakeFrames(WREN_RIGHT);

  art.wren = {
    down: bakeFrames(WREN_DOWN),
    up: bakeFrames(WREN_UP),
    right,
    left: right.map(flipH),
  };

  // Flash frames for the invulnerability blink, derived rather than authored.
  art.wrenFlash = {
    down: art.wren.down.map((c) => silhouette(c, 'white')),
    up: art.wren.up.map((c) => silhouette(c, 'white')),
    right: art.wren.right.map((c) => silhouette(c, 'white')),
    left: art.wren.left.map((c) => silhouette(c, 'white')),
  };

  art.spitter = bakeFrames(SPITTER);
  art.hermit = bakeFrames(HERMIT)[0];
  art.rock = bakeFrames(ROCK_SHOT)[0];
  art.rupee = bakeFrames(RUPEE)[0];
  art.poof = bakeFrames(POOF);

  const swordRight = bakeFrames(SWORD_RIGHT)[0];
  art.sword = {
    up: bakeFrames(SWORD_UP)[0],
    down: bakeFrames(SWORD_DOWN)[0],
    right: swordRight,
    left: flipH(swordRight),
  };

  art.heart = {
    full: bake(HEART_FULL, LIFE),
    half: bake(HEART_HALF, LIFE),
    empty: bake(HEART_EMPTY, LIFE),
  };
}
