using LeadingEDJE.Leap.Api.Modules.Compass;
using LeadingEDJE.Leap.Api.Modules.Compass.Data.SeedData;
using LeadingEDJE.Leap.Api.Platform.Data;
using Microsoft.EntityFrameworkCore;
using Shouldly;

namespace LeadingEDJE.Leap.Api.Tests.Compass;

/// <summary>
/// Pins that <see cref="CompassDirectorySeeder"/> assigns STABLE identifiers, so a re-seed cannot
/// silently change what an existing cross-module reference points at.
/// </summary>
/// <remarks>
/// <para>
/// This locks existing behaviour rather than introducing it. The seeder already assigns every
/// identifier explicitly and uses no <c>Random</c>; its own header says the graph is byte-identical
/// on every run. This test exists so that property cannot regress unnoticed, because the consequence
/// of losing it is unusually nasty.
/// </para>
/// <para>
/// Why identifier stability is load-bearing (owner decision D-2). Timesheet and OOTO reference
/// Compass records by their native <c>integer</c> keys. Those columns are
/// <c>generated by default as identity</c>, so if the seeder ever stopped supplying explicit values,
/// Postgres would assign its own on a re-seed and every stored reference would come to mean a
/// DIFFERENT employee. Not a dangling reference — a wrong one, resolving successfully to the wrong
/// person, with nothing to detect it. Under D-3 there is no foreign key to object, either.
/// </para>
/// <para>
/// The residual hazard this test does NOT cover is recorded in the feature's severance record
/// (FR-019a): importing real directory data will assign different identifiers than the synthetic
/// seed, and every stored cross-module reference must be remapped at that point. That is a
/// documented breaking operation, not something an assertion can prevent.
/// </para>
/// <para>
/// InMemory is the right provider here. The property under test is which identifiers the seeder
/// CHOOSES, which is decided in C# before any provider sees a row;
/// <c>PostgresSequenceSync</c> no-ops on a non-relational provider by design.
/// </para>
/// </remarks>
public class CompassSeedDeterminismTests
{
    /// <summary>An arbitrary but fixed anchor, so nothing in the test depends on the wall clock.</summary>
    private static readonly DateOnly Anchor = new(2026, 8, 10);

    private static LeapDbContext CreateContext() =>
        new(new DbContextOptionsBuilder<LeapDbContext>()
            .UseInMemoryDatabase($"CompassSeedDeterminismDb_{Guid.NewGuid():N}")
            .Options);

    private static async Task<(List<int> Employees, List<int> Clients)> SeedAndReadIdsAsync(DateOnly today)
    {
        using var context = CreateContext();
        await CompassDirectorySeeder.SeedAsync(context, today, TestContext.Current.CancellationToken);

        var employees = await context.Set<Employee>()
            .AsNoTracking()
            .Select(e => e.Id)
            .OrderBy(id => id)
            .ToListAsync(TestContext.Current.CancellationToken);

        var clients = await context.Set<Client>()
            .AsNoTracking()
            .Select(c => c.Id)
            .OrderBy(id => id)
            .ToListAsync(TestContext.Current.CancellationToken);

        return (employees, clients);
    }

    [Fact]
    public async Task Seeder_AssignsIdenticalIdentifiers_AcrossSeparateRuns()
    {
        // Arrange — two independent databases, same anchor date.

        // Act
        var first = await SeedAndReadIdsAsync(Anchor);
        var second = await SeedAndReadIdsAsync(Anchor);

        // Assert
        second.Employees.ShouldBe(first.Employees);
        second.Clients.ShouldBe(first.Clients);
    }

    [Fact]
    public async Task Seeder_AssignsIdentifiers_ThatDoNotDependOnTheAnchorDate()
    {
        // Arrange — the same seed run a year apart. Dates in the seeded graph are expected to
        // differ; identifiers are not, because a reference stored by another module must keep
        // meaning the same person no matter when the directory was seeded.

        // Act
        var seededToday = await SeedAndReadIdsAsync(Anchor);
        var seededNextYear = await SeedAndReadIdsAsync(Anchor.AddYears(1));

        // Assert
        seededNextYear.Employees.ShouldBe(seededToday.Employees);
        seededNextYear.Clients.ShouldBe(seededToday.Clients);
    }

    [Fact]
    public async Task Seeder_AssignsContiguousIdentifiersFromOne()
    {
        // Arrange — the property, not the size: both sets have grown since the 2026-08-10 baseline
        // (employees 1..97, clients 1..28) and both are still contiguous from 1, which is what this
        // asserts. A gap or an offset means identifier assignment changed, which invalidates every
        // stored cross-module reference.

        // Act
        var (employees, clients) = await SeedAndReadIdsAsync(Anchor);

        // Assert
        employees.ShouldBe([.. Enumerable.Range(1, employees.Count)]);
        clients.ShouldBe([.. Enumerable.Range(1, clients.Count)]);
    }
}
